[package]
name = "cactus"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
eframe = "0.32.0"
egui_extras = "0.32.0"
image = "0.25.6"
rand = "0.9.2"
resvg = "0.45.1"
rodio = "0.21.1"
tiny-skia = "0.11.4"
usvg = "0.45.1"
