[package]
name = "cactus-gui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
libcactus = {path = "../libcactus"}
raylib = { version = "5.5.1", features = ["wayland"] }
