name: CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'Makefile'
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'vendor/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'Makefile'
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'vendor/**'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential clang-format g++

      - name: Install build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc clang-format make

      - name: Install build tools (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make

      - name: Fix make alias (Windows)
        if: runner.os == 'Windows'
        run: |
          ln -s /ucrt64/bin/mingw32-make.exe /ucrt64/bin/make
        shell: msys2 {0}

      - name: Run tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          make clean
          make test

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          make clean
          make test
        shell: msys2 {0}